use_frameworks!

target 'Moya-SwiftyJSON_Example' do
  pod 'Moya-SwiftyJSON', :path => '../'

  target 'Moya-SwiftyJSON_Tests' do
    inherit! :search_paths

    # pod 'Quick', '~> 1.2.0'
    # pod 'Nimble', '~> 7.0.2'
  end
end
